CREATE TABLE DistanceData (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status VARCHAR(255),
  data VARCHAR(255),
  value INT
);