CREATE TABLE LoraData (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  light DECIMAL(5,2),
  humidity DECIMAL(5,2),
  temperature DECIMAL(5,2),
  presence BOOLEAN
);